### ISSUE TITLE
Every filter is an autocomplete field

### ISSUE THREAD

**Issue by berarma** [FriendsOfCake/crud-view#315]
When autocomplete is true, it forces every filter field to be an autocomplete select. It doesn't matter the name of the field or the field options set in the SearchManager or the ViewSearch listener.

Setting autocomplete to false solves the issue but this renders the option useless.

**Comment by ADmad** [comment]
Have you tried setting the inputType data attribute for the field to "text" for the ones you want to be text? That's what the JS code checks for https://github.com/FriendsOfCake/crud-view/blob/master/webroot/js/local.js#L57

**Comment by ADmad** [comment]
Sorry, I missed understood the issue. You can set the autocomplete config to false and then add `autocomplete` class to required fields.

**Comment by ADmad** [comment]
Not sure what the original author intended. But I agree the default doesn't make much sense.

**Comment by ADmad** [comment]
Given that the problem is circumvented by setting `autocomplete` to `false` I am going to keep this unchanged for now. In any case all the options jugging for autocomplete belongs in a widget class instead of the listener. I have an open issue #272 for creating the widget since quite sometime but haven't got around to it.

**Comment by ADmad** [comment]
Autocomplete is now used by default only for `select`: 21d75e8f232db365536f757cbaa28b0e5371ea38
